### ISSUE TITLE
Error while doing update.

### ISSUE THREAD

**Issue by kirillVv** [ricklancee/maljs#5]
Hello,

i've been getting an error while using the update function.

Error : `"<div>There was a MySQL Error. The staff has been notified and is looking in to it. We apologize for the inconvenience.Updated"`

Part of the code if needed where i try to update  : 

    `if (CancelFunc === false) {
            id = tableData.id; // -> 100% right id ( proved )
            status = watchingStatus;  // -> // 1, 2, 3, 4 or 6
            my_score = tableData.my_score;  // -> from 1 to 10
            epwatched = tableData.epwatched; // -> can't be bigger than total episodes

            await api.anime.update(
                 id,{score: my_score}
            ).then( result => {  
                 console.log(result);  // -> That message is being shown here.
            }).catch(err => { console.log(err); });
     }`

Writing just to make you know about that.

**Comment by ricklancee** [comment]
Could you try wrapping score in a data object, and see if that works (see below)? Looks like there is something wrong with either the data or MyAnimeList has some issues with the api currently. My calls seem to be working fine. 

Like this:
```
await api.anime.update(
id, {data: {score: my_score}}
)
```

I will investigate further

**Comment by kirillVv** [comment]
Sory for the delay.

I have tried wrapping in a data object ,  have also tried to give id and score manually but still get same error.

**Comment by ricklancee** [comment]
Hi @kirillVv!

I've run these update calls in nodejs and the browser and they work fine. It seems to be not a problem with this api wrapper but with either the MyAnimeList servers (if so can you update the show via the myanimelist site?) or the anime you are trying to update has a bad id or something...? Can you update other anime?

Things i've done to test:

- Created a new myanimelist user.
- Added https://myanimelist.net/anime/35062 to my watch list
- Run the following script in the browser and node. 

Result: Api Response was "Updated" and the show was updated on my list.

```
// var MALjs = require('MALjs') // for node 
var api = new MALjs(someusername, somepassword);

api.anime.update('35062', {
  score: '8'
})
.then(result => {
  console.log(JSON.stringify(result, null, 2))
})
.catch(err => {
  console.log('Something went wrong!', err.stack);
});
```

**Comment by kirillVv** [comment]
I am doing exactly same as you but no success. Still getting the `"<div>There was a MySQL Error. The staff has been notified and is looking in to it. We apologize for the inconvenience.Updated"` response.

Im doing it in nw.js and have uploaded a test project with 2 input fields and a button to test update function. It works as normal browser + node but on desktop.
If you have good mood and free time can you please check it ?

https://github.com/kirillVv/test_api/releases/tag/0.0.0

**Comment by ricklancee** [comment]
This seems to be an issue with either MyAnimeList, your own application or this library is not compatible with nw.js (if not i might test and try to make it compatible sometime). So i'm closing this issue since i cannot find a fix for your problem, sorry.

If this library is not working with your app you could try working with the MAL api directly and see if you encounter any problems there. https://myanimelist.net/modules.php?go=api
